#数据源配置
server:
  port: 8103
#管理端口
management:
  server:
    port: -1

spring:
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}
