version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  clickhouse:
    image: clickhouse/clickhouse-server:23
    ports:
      - "8123:8123"
      - "9000:9000"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  kafka:
    image: bitnami/kafka:3
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  minio:
    image: minio/minio:RELEASE.2024-03-15T23-56-19Z
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9001:9000"

  rule-engine:
    build:
      context: ..
      dockerfile: services/rule-engine/Dockerfile
    environment:
      DB_URL_PG: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      DB_URL_CH: tcp://clickhouse:9000
      KAFKA_BROKERS: kafka:9092
      REDIS_URL: redis://redis:6379
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    depends_on:
      - postgres
      - clickhouse
      - kafka
      - redis
      - minio
