#服务器端口
server:
  port: 8109

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dataQuality.dev.url}
    username: ${blade.datasource.dataQuality.dev.username}
    password: ${blade.datasource.dataQuality.dev.password}
