#服务器端口
server:
  port: 8109
#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dataQuality.test.url}
    username: ${blade.datasource.dataQuality.test.username}
    password: ${blade.datasource.dataQuality.test.password}
