#服务器端口
server:
  port: 6001

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.platform.test.url}
    username: ${blade.datasource.platform.test.username}
    password: ${blade.datasource.platform.test.password}
