#服务器端口
server:
  port: 6001

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.platform.dev.url}
    username: ${blade.datasource.platform.dev.username}
    password: ${blade.datasource.platform.dev.password}
