#服务器端口
server:
  port: 6001

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.platform.prod.url}
    username: ${blade.datasource.platform.prod.username}
    password: ${blade.datasource.platform.prod.password}

