knife4j:
  cloud:
    routes:
      - name: 授权模块
        uri: 127.0.0.1
        location: /blade-auth/v2/api-docs
      - name: 工作台模块
        uri: 127.0.0.1
        location: /blade-desk/v2/api-docs
      - name: 系统模块
        uri: 127.0.0.1
        location: /blade-system/v2/api-docs
#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
