knife4j:
  cloud:
    routes:
      - name: 授权模块
        uri: 192.168.0.157:88
        location: /blade-auth/v2/api-docs
      - name: 工作台模块
        uri: 192.168.0.157:88
        location: /blade-desk/v2/api-docs
      - name: 系统模块
        uri: 192.168.0.157:88
        location: /blade-system/v2/api-docs
#数据源配置
spring:
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}
